title: Vancouver Jazz Exchange
description: A meetup to discuss jazz and socialize
future: true
url: ""
baseurl: ""
port: 4010
meetupcom: https://www.meetup.com/vancouver-jazz-exchange/events/
permalink: /archives/:year-:month-:day

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "meetup"
      category: "archive"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .idea/
  - justfile
  - README.md
  - CNAME
